version = 0.1
[default.deploy.parameters]
stack_name = "tkasu-aws-serverless-data-pipeline"
resolve_s3 = true
s3_prefix = "tkasu-aws-serverless-data-pipeline"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["UpdaterFunction=972829804869.dkr.ecr.eu-west-1.amazonaws.com/tkasuawsserverlessdatapipeline867fba1d/updaterfunction78c32005repo"]
parameter_overrides = "DataBucketName=\"github-statistics-data\""
