version = 0.1
[default.deploy.parameters]
stack_name = "aws-kerho-demo-tkasu-poller"
resolve_s3 = true
s3_prefix = "aws-kerho-demo-tkasu-poller"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
