AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Poller

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  PollerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: poller/
      Handler: poller.handle.handler
      Runtime: python3.9
      Architectures:
        - arm64
      Policies:
        - S3FullAccessPolicy:
            BucketName: ew1-dev-awskerho-tomi-data
        - SSMParameterReadPolicy:
            ParameterName: poller-github-api-key
